version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: blog-mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  mongo_data: 