version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: blog-mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-network

  mongo-express:
    image: mongo-express
    container_name: blog-mongo-admin
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  mongo_data:
